name: Viciont_Hardcore3_Plugin
version: ${project.version}
main: vct.hardcore3.ViciontHardcore3
author: CrissyJuanXD
api-version: 1.21
commands:
  revive:
    description: Revive a player.
    usage: /revive <player>
    permission: viciont_hardcore3.revive
    permission-message: No tienes permiso para usar este comando.
  revivecoords:
    description: Configura las coordenadas del revive.
    usage: /revivecoords <x> <y> <z>
    permission: viciont_hardcore3.revivecoords
    permission-message: No tienes permiso para usar este comando.
  resetdeathstorm:
    description: Resetea la DeathStorm
    usage: /resetdeathstorm
    permission: viciont_hardcore3.resetdeathstorm
    permission-message: No tienes permiso para usar este comando.
  adddeathstorm:
    description: Añade horas a la DeathStorm
    usage: /adddeathstorm <horas>
    permission: viciont_hardcore3.adddeathstorm
    permission-message: No tienes permiso para usar este comando.
  removedeathstorm:
    description: Remueve horas de la DeathStorm
    usage: /removedeathstorm
    permission: viciont_hardcore3.removedeathstorm
    permission-message: No tienes permiso para usar este comando.
  stopdeathstorm:
    description: Detiene la DeathStorm
    usage: /stopdeathstorm
    permission: viciont_hardcore3.stopdeathstorm
    permission-message: No tienes permiso para usar este comando.
  cambiardia:
    description: Cambia manualmente al día especificado
    usage: /cambiardia <día>
    permission: viciont_hardcore3.cambiardia
    permission-message: No tienes permiso para usar este comando.
  giveessence:
    description: Da al jugador una esencia específica.
    usage: /giveessence <nombre de esencia>
    permission: viciont_hardcore3.giveessence
    permission-message: No tienes permiso para usar este comando.
  ruletavct:
    description: Comando para reproducir la animación de la ruleta.
    usage: /ruletavct <json>
    permission: viciont_hardcore3.ruletavct
    permission-message: No tienes permiso para usar este comando.
  muertevct:
    description: Comando para reproducir la animación de la Muerte.
    usage: /muertevct <json>
    permission: viciont_hardcore3.muertevct
    permission-message: No tienes permiso para usar este comando.
  bonusvct:
    description: Comando para reproducir la animación de Bonus.
    usage: /bonusvct <json>
    permission: viciont_hardcore3.bonusvct
    permission-message: No tienes permiso para usar este comando.
  structure:
    description: Genera estructuras especiales en el mundo
    usage: /structure <nombre>
    permission: vicionthardcore3.command.estructure
    permission-message: No tienes permiso para usar este comando.
  start:
    description: Start the game
    usage: /start <evento1|skybattle|force|logros>
    aliases: []
    permission: viciont_hardcore3.command.start
    permission-message: No tienes permiso para usar este comando.
  end:
    description: End the game
    usage: /end <evento1|logros>
    aliases: []
    permission: viciont_hardcore3.command.end
    permission-message: No tienes permiso para usar este comando.
  evento1:
    description: Administra participantes del evento1.
    usage: /evento participantes <list|add|remove> [jugador]
    aliases: [ ]
    permission: viciont_hardcore3.command.evento1
    permission-message: No tienes permiso para usar este comando.
  reset:
    description: Resetea el evento.
    usage: /reset <logros>
    aliases: []
    permission: viciont_hardcore3.command.reset
    permission-message: No tienes permiso para usar este comando.
  logros:
    description: Comando para ver los logros.
    usage: /logros
  addlogro:
    description: Añade un logro a un jugador.
    usage: /addlogro <nombrelogro> <jugador> [item_lista|all]
    permission: viciont_hardcore3.command.addlogro
    permission-message: No tienes permiso para usar este comando.
  removelogro:
    description: Remueve un logro a un jugador.
    usage: /removelogro <nombrelogro> <jugador> [item_lista|all]
    permission: viciont_hardcore3.command.removelogro
    permission-message: No tienes permiso para usar este comando.
  magictp:
    description: Teletransporta jugadores a coordenadas especificadas con efectos especiales.
    usage: /magictp <jugador o @a> <x y z | spawn>
    permission: viciont_hardcore3.command.magic
    permission-message: No tienes permiso para usar este comando.
  playdisco:
    description: Iniciar el efecto disco.
    usage: /playdisco
    permission: viciont_hardcore3.command.playdisco
    permission-message: No tienes permiso para usar este comando.
  stopdisco:
    description: Detener el efecto disco.
    usage: /stopdisco
    permission: viciont_hardcore3.command.stopdisco
    permission-message: No tienes permiso para usar este comando.
  spawnvct:
    description: Spawnea un mob personalizado en tu ubicación
    usage: /spawnvct <mob> [jugador (opcional)] [x] [y] [z]
    permission: viciont_hardcore3.command.spawnvct
    permission-message: No tienes permiso para usar este comando.
  addtiempo:
    description: Añade un temporizador en la bossbar.
    usage: /addtiempo [nombre opcional] <tiempo> [on/off]
    permission: viciont_hardcore3.command.addtiempo
    permission-message: No tienes permiso para usar este comando.
  removetiempo:
    description: Elimina un temporizador de la bossbar.
    usage: /removetiempo [nombre opcional]
    permission: viciont_hardcore3.command.removetiempo
    permission-message: No tienes permiso para usar este comando.
  tiempoview:
    description: Muestra los temporizadores activos en la bossbar.
    usage: /tiempoview <jugador/all>
    permission: viciont_hardcore3.command.tiempoview
    permission-message: No tienes permiso para usar este comando.
  givevct:
    description: Da un item especial del plugin a un jugador.
    usage: /givevct <item> [cantidad] [jugador]
    permission: viciont_hardcore3.command.givevct
    permission-message: No tienes permiso para usar este comando.
  addnightmare:
    description: Añade el evento Nightmare a un jugador o a todos.
    usage: /addnightmare <player|@a>
    permission: viciont_hardcore3.command.addnightmare
    permission-message: No tienes permiso para usar este comando.
  removenightmare:
    description: Remueve el evento Nightmare a un jugador o a todos.
    usage: /removenightmare <player|@a>
    permission: viciont_hardcore3.command.removenightmare
    permission-message: No tienes permiso para usar este comando.
  resetnightmarecooldown:
    description: Resetea el cooldown del evento Nightmare a un jugador o a todos.
    usage: /resetnightmarecooldown <player|@a>
    permission: viciont_hardcore3.command.resetnightmarecooldown
    permission-message: No tienes permiso para usar este comando.
  levelnightmare:
    description: Ajusta el nivel de la pesadilla
    usage: /levelnightmare <jugador|@a> <Nvl1/Nvl2/Nvl3>
    permission: viciont_hardcore3.command.levelnightmare
    permission-message: No tienes permiso para usar este comando.
  givespawner:
    description: Da un spawner personalizado que genera mobs custom.
    usage: /givespawner <mob> [jugador] | /givespawner vanilla <mob_vanilla> [jugador]
    permission: viciont_hardcore3.command.givespawner
    permission-message: No tienes permiso para usar este comando.
  reloadcustomspawn:
    description: Recarga todos los spawners custom en el mundo
    usage: /reloadcustomspawn
    permission: viciont_hardcore3.command.givespawner
    permission-message: No tienes permiso para usar este comando.
  activarmision:
    description: Activa una misión específica
    usage: /activarmision <número>
    permission: viciont_hardcore3.missions.admin
    permission-message: No tienes permiso para usar este comando.
  desactivarmision:
    description: Desactiva una misión específica
    usage: /desactivarmision <número>
    permission: viciont_hardcore3.missions.admin
    permission-message: No tienes permiso para usar este comando.
  misiones:
    description: Abre la interfaz del sistema de misiones
    usage: /misiones
  addmision:
    description: Añade una misión completada a un jugador
    usage: /addmision <jugador> <número>
    permission: viciont_hardcore3.missions.admin
    permission-message: No tienes permiso para usar este comando.
  removemision:
    description: Remueve una misión completada de un jugador
    usage: /removemision <jugador> <número>
    permission: viciont_hardcore3.missions.admin
    permission-message: No tienes permiso para usar este comando.
  penalizadosmisiones:
    description: Muestra la lista de jugadores penalizados por misiones
    usage: /penalizadosmisiones
    permission: viciont_hardcore3.missions.admin
    permission-message: No tienes permiso para usar este comando.
  spawntienda:
    description: Spawnea una tienda (aldeano) en las coordenadas especificadas
    usage: /spawntienda <Monedas|Utilidades|Varios> [x] [y] [z]
    permission: viciont_hardcore3.shop.admin
    permission-message: No tienes permiso para usar este comando.
  spawnslotmachine:
    description: Spawn a slot machine at your location
    usage: /<command>
    permission: viciont.slotmachine.spawn
  giveslotmachine:
    description: Give slot machine item to a player
    usage: /<command> [player] [amount]
    permission: viciont.slotmachine.give
  slotmachine:
    description: Slot machine management commands
    usage: /<command> <spawn|give|remove|reload|info>
    permission: viciont.slotmachine.admin
    aliases: [sm, slotm]
  spawnportalce:
    description: Crea un portal al Corrupted End en el overworld
    usage: /spawnportalce [<x> <y> <z> | random]
    permission: viciont_hardcore3.spawnportal.admin
    permission-message: No tienes permiso para usar este comando.
  givelootable:
    description: Da una caja de loot del Corrupted End a un jugador
    usage: /givelootable <tipo> <jugador>
    permission: viciont_hardcore3.giveloot.admin
    permission-message: No tienes permiso para usar este comando.
  flashlight:
    description: Recarga la configuración de las linternas
    usage: /flashlight reload
    permission: viciont_hardcore3.flashlight.admin
    permission-message: No tienes permiso para usar este comando.
  mobcap:
    description: Comando principal para gestionar MobCap
    usage: /mobcap <info|setbase|doble|triple|normal|habilitar|deshabilitar|reset|reload|mob>
    permission: viciont_hardcore3.mobcap.admin
    aliases: [ mc, mobcapmanager ]
  mobcapinfo:
    description: Muestra información detallada del MobCap
    usage: /mobcapinfo
    permission: viciont_hardcore3.mobcap.admin
    aliases: [ mcinfo, mobcapstatus ]
  habilidades:
    description: Muestra las habilidades desbloqueadas de un jugador
    usage: /habilidades <jugador>
  reloadevent:
    description: Recarga configuraciones internas del plugin.
    usage: /reloadevent <itempartyconfig>
    permission: viciont_hardcore3.command.reload
    permission-message: No tienes permiso para usar este comando.
  viciont:
    description: Comandos públicos del servidor Viciont.
    usage: /viciont <subcomando>
  ca:
    description: Gestiona la corrupcion ansiosa de los jugadores.
    usage: /ca <add/remove/reset/disable/enable> [jugador] [porcentaje].
    permission: viciont_hardcore3.command.ca
    permission-message: No tienes permiso para usar este comando.
  debugarena:
    description: Activa el modo debug de arenas.
    usage: /debugarena
    permission: viciont_hardcore3.command.debugarena
    permission-message: No tienes permiso para usar este comando.
  testtoast:
    description: Prueba un toast personalizado
    usage: /<command>
depend:
  - NBTAPI
softdepend:
  - PlaceholderAPI
  - StreamEvents
  - BetterRevive
  - Multiverse-Core
  - ProtocolLib
