name: Viciont_Hardcore3_Plugin
version: 1.4.2
main: vct.hardcore3.ViciontHardcore3
author: CrissyJuanXD
api-version: 1.21
commands:
  revive:
    description: Revive a player.
    usage: /revive <player>
  resetdeathstorm:
    description: Resetea la DeathStorm
    usage: /resetdeathstorm
    permission: viciont_hardcore3.resetdeathstorm
    permission-message: No tienes permiso para usar este comando.
  adddeathstorm:
    description: Añade horas a la DeathStorm
    usage: /adddeathstorm <horas>
    permission: viciont_hardcore3.adddeathstorm
    permission-message: No tienes permiso para usar este comando.
  removedeathstorm:
    description: Remueve horas de la DeathStorm
    usage: /removedeathstorm
    permission: viciont_hardcore3.removedeathstorm
    permission-message: No tienes permiso para usar este comando.
  cambiardia:
    description: Cambia manualmente al día especificado
    usage: /cambiardia <día>
    permission: viciont_hardcore3.cambiardia
    permission-message: No tienes permiso para usar este comando.
  dia:
    description: Muestra el día actual de Viciont Hardcore 3
    usage: /dia
  ping:
    description: Muestra tu ping actual en milisegundos.
    usage: /ping
  giveessence:
    description: Da al jugador una esencia específica.
    usage: /giveessence <nombre de esencia>
    permission: viciont_hardcore3.giveessence
    permission-message: No tienes permiso para usar este comando.
  ruletavct:
    description: Comando para reproducir la animación de la ruleta.
    usage: /ruletavct <json>
    permission: viciont_hardcore3.ruletavct
    permission-message: No tienes permiso para usar este comando.
  muertevct:
    description: Comando para reproducir la animación de la Muerte.
    usage: /muertevct <json>
    permission: viciont_hardcore3.muertevct
    permission-message: No tienes permiso para usar este comando.
  bonusvct:
    description: Comando para reproducir la animación de Bonus.
    usage: /bonusvct <json>
    permission: viciont_hardcore3.bonusvct
    permission-message: No tienes permiso para usar este comando.
  vcth:
    description: Localiza y maneja las estructuras de Corrupted Villages.
    usage: /<command> locate Corrupted_Village
    permission: vicionthardcore3.command.vcth
    permission-message: No tienes permiso para usar este comando.
  estructure:
    description: Localiza y maneja las estructuras de Vicion
    usage: /estructure <CorruptedVillage>
    permission: vicionthardcore3.command.estructure
    permission-message: No tienes permiso para usar este comando.

